### ISSUE TITLE
Fix collection error when removing a collection

### ISSUE THREAD

**Issue by Lamarcke** [game-node-app/game-node-web#46]
Log:
```
Nest] 29  - 03/19/2024, 7:40:38 PM   ERROR [ExceptionsHandler] Cannot delete or update a parent row: a foreign key constraint fails (gamenode.collection_entry_collections_collection, CONSTRAINT FK_9e6cd997dc83364622420a5cf42 FOREIGN KEY (collectionId) REFERENCES collection (id))

QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails (gamenode.collection_entry_collections_collection, CONSTRAINT FK_9e6cd997dc83364622420a5cf42 FOREIGN KEY (collectionId) REFERENCES collection (id))

    at Query.onResult (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)

    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:36:14)

    at PoolConnection.handlePacket (/app/node_modules/mysql2/lib/c
```

**Comment by Lamarcke** [comment]
Not only has this been fixed, but possible errors related to notifications, statistics, user views and likes that would happen when a parent entity is deleted have also been fixed by making correct use of `ON DELETE` cascades.
